### ISSUE TITLE
cc email address being overridden by default gallery email once app is closed and reopened

### ISSUE THREAD

**Issue by garrengotthardt** [artsy/energy#109]
@sarahscott worked with Gemma today to confirm we understood and could replicate the issue related to the CC email address that Lazarides (slug = "lazarides") reported last week. 

the issue as they described was that they continually set the default email to info@lazinc.com but whenever they reopen the app the email is reset to info@lazarides.com. They claim to have never set this email but as it turns out they had it set as the default gallery email (since changed to patch this issue) in CMS at https://cms.artsy.net/settings?current_partner_id=lazarides. 

![screen shot 2015-11-30 at 3 09 57 pm](https://cloud.githubusercontent.com/assets/1863593/11484091/3c3dccac-977a-11e5-9575-ecc995d45511.png)

Was able to replicate with the following:

1. downloaded/synced their content and no CC email is set by default
2. set email to desired email (info@lazinc.com), saved, and was able to pull up an email draft with it correctly CC'd
![image-1](https://cloud.githubusercontent.com/assets/1863593/11484223/e27a2a98-977a-11e5-8224-413664ca9cc2.jpg)
3. on quitting and reopening the app the cc'd address is set to the default gallery address set on the partner in CMS
![image-2](https://cloud.githubusercontent.com/assets/1863593/11484245/f86c65aa-977a-11e5-982b-7ba9933e9a7a.jpg)
![image-3](https://cloud.githubusercontent.com/assets/1863593/11484249/fcf90cd6-977a-11e5-955a-184de664db83.jpg)

have temporarily patched this partners issue by changing the email for them in CMS to the desired email but the issue still would stand in the case that their default cc'd address is not the public gallery email 

let me know if i can provide any further details

**Comment by sarahscott** [comment]
@garrengotthardt this is a beautifully detailed issue :raised_hands: 

I fixed it in the new settings (PR #108) and we should definitely add this to the QA process to make sure it works consistently. I'll close this issue once the email PR is merged.

Danke!

**Comment by garrengotthardt** [comment]
@sarahscott great thanks so much!

**Comment by sarahscott** [comment]
This actually wasn't fixed in that PR; should be fixed during the current milestone
