### ISSUE TITLE
Disable or hide Sync button upon tap

### ISSUE THREAD

**Issue by sarahscott** [artsy/energy#123]
Should it become a spinner or grey out?

**Comment by orta** [comment]
Ideally should show a progress bar + estimate?

**Comment by lucaderosso** [comment]
love the progress bar. it seems that having more real estate on that view is going to become quite handy soon!

**Comment by sarahscott** [comment]
@lucaderosso do you think a progress bar like this would work? black-on-white, of course.

![simulator screen shot dec 21 2015 4 11 35 pm](https://cloud.githubusercontent.com/assets/2712962/11944812/a3ae5d50-a7fd-11e5-9387-dd0e8d0d466c.png)

**Comment by lucaderosso** [comment]
@sarahscott thanks for reminding me we had one already ;) so i made this:

![folio_ipad_p_settings-syncing-progress](https://cloud.githubusercontent.com/assets/539004/11980460/f21c4d64-a968-11e5-9a10-fea1190a0330.jpg)

**Comment by sarahscott** [comment]
:clap: looks great!
