### ISSUE TITLE
Disable email button for installation shots

### ISSUE THREAD

**Issue by sarahscott** [artsy/energy#126]
If you're viewing a show's installation shots, you can select images to send in an email but you're not allowed to compose anything. Should be disabled here

**Comment by sarahscott** [comment]
Also a problem here with documents

**Comment by sarahscott** [comment]
Also disable add-to-album

**Comment by orta** [comment]
Think a better approach is to fix selecting documents and install shots, but to make sure the "compose" email button only becomes active when there are artworks or documents

**Comment by orta** [comment]
And to disable select-all in installation shots

**Comment by garrengotthardt** [comment]
found a related / different issue in https://github.com/artsy/energy/issues/217 but closing this
