### ISSUE TITLE
WiFi status messaging for sync view

### ISSUE THREAD

**Issue by lucaderosso** [artsy/energy#129]
NOTE - I couldn't find the related issue to attach this too so I made I new one. 

**About**
Provide information about the current wifi status on the sync view inside the settings view.
Icons can be found here: https://www.dropbox.com/sh/5yi3vyjd32aki94/AACSwf0EKr5OGxgR8jTt_ndaa?dl=0

![folio_ipad_p_settings-sync-wifi-off](https://cloud.githubusercontent.com/assets/539004/11980676/a786c7fa-a96a-11e5-9781-6b0daffe2a8c.jpg)
Wi-Fi is off:
- [ ] GG main copy edit: "Click the button below to sync any new artworks, documents, or information added in CMS with Folio. Given the large size of images, before syncing, please ensure you have a strong WiFi connection."
- [ ] GG WiFi status copy edit: "Your WiFi is turned off. Please turn it on to start syncing."

![folio_ipad_p_settings-sync-wifi-weak](https://cloud.githubusercontent.com/assets/539004/11980677/a78a51fe-a96a-11e5-903b-d2d17574e8ba.jpg)
WiFi signal is weak:
- [ ] GG main copy edit: "Click the button below to sync any new artworks, documents, or information added in CMS with Folio. Given the large size of images, before syncing, please ensure you have a strong WiFi connection."
- [ ] GG WiFi status copy edit edit: "Your WiFi signal is weak. We recommend seeking a stronger signal for the fastest sync."

![folio_ipad_p_settings-sync-wifi-strong](https://cloud.githubusercontent.com/assets/539004/11980678/a78b47a8-a96a-11e5-9275-4e9d7f7f0bcc.jpg)
WiFi signal is strong:
- [ ] GG main copy edit: "Click the button below to sync any new artworks, documents, or information added in CMS with Folio. Given the large size of images, before syncing, please ensure you have a strong WiFi connection."
- [ ] GG WiFi status copy: "Your WiFi signal is strong." (don't think there needs to be a second part to this here)

**Comment by lucaderosso** [comment]
@garrengotthardt feel free to suggest copy edits.

**Comment by dblock** [comment]
I find it missing a period in "WiFi is OFF. Turn in ON to start synching" at the end. If those are two complete phrases. Similarly for everything else, should be consistent.

**Comment by garrengotthardt** [comment]
thanks @dblock, agree

@lucaderosso / @sarahscott added copy specifics inline to the first piece of the issue above - let me know if there are any questions/concerns

**Comment by sarahscott** [comment]
Fixed in #131
