### ISSUE TITLE
[Analytics] Spotty partner identification

### ISSUE THREAD

**Issue by anipetrov** [artsy/energy#174]
Becca initially noticed multiple partners with relative size NULL appearing in the monthly uniques chart on the [folio stats dashboard](http://gallery-experience.artsy.net/metrics/folio):
![image](https://cloud.githubusercontent.com/assets/8701687/12952773/b22a34fc-cfe5-11e5-90fe-dcb79cadd86d.png)

Took a further look into number of user (non-admin) screenviews fired for unidentified partners (partner_relative_size property is NULL), and it looks like we started to get significantly more since Jan 27 (did we have a release around then?). Query (you can run in SQL Runner tab in looker):
```sql
SELECT received_at::DATE,
       COUNT(id) as unidentified_screenviews_fired
FROM folio.screens
WHERE partner_relative_size IS NULL
AND   user_type = 'User'
GROUP BY received_at::DATE
ORDER BY received_at::DATE DESC LIMIT 100
```

result:
![image](https://cloud.githubusercontent.com/assets/8701687/12953158/3ffbf68e-cfe7-11e5-9d99-d55998b37697.png)

**Comment by orta** [comment]
Yep, there was a release: https://github.com/artsy/energy/blob/orta-cp-frameworks/docs/CHANGELOG.yml

Must be a regression :+1:

**Comment by sarahscott** [comment]
This is related to a change in gravity: https://github.com/artsy/gravity/pull/9621

The relative_size was traditionally a string; now it's an to be an int and sizes **1a** and **1b** are to be grouped into **1**. It'll require a small migration - shouldn't be too crazy.
