### ISSUE TITLE
VIR doesn't fit the screen on an iPad Pro

### ISSUE THREAD

**Issue by orta** [artsy/energy#200]
it's probably very hardcoded to the iPad's original 1024x768

![img_2564](https://cloud.githubusercontent.com/assets/49038/14977173/ce1c3fb0-1109-11e6-9f33-4a1ccbdf895f.JPG)

VIR needs a whole consolidation for energy/eigen - we have three separate implementations.

**Comment by garrengotthardt** [comment]
@orta just noting additionally here that there is no way to get out of VIR when in this view (the "Done" button has disappeared)

![vir](https://cloud.githubusercontent.com/assets/1863593/15019765/5be9b654-11ed-11e6-9d1a-7f93a0a2c5f4.gif)

**Comment by orta** [comment]
The button has disappeared, aye, but it's a black button, you can press in the top corner where it should show and it will go back 👍

**Comment by garrengotthardt** [comment]
Ahh got it i was trying to click in the corner of the image rather than the screen

**Comment by orta** [comment]
Fixed in 2.5.4
