### ISSUE TITLE
Fix NSInvalidArgumentException in - [ARSpotlightExporter itemForArtwork:], line 83

### ISSUE THREAD

**Issue by artsyit** [artsy/energy#223]
### Stacktrace

<pre>ARSpotlightExporter;itemForArtwork:;ARSpotlightExporter.m;83
NSArray(ObjectiveSugar);map:;NSArray+ObjectiveSugar.m;99
ARSpotlightExporter;artworkResults;ARSpotlightExporter.m;69
ARSpotlightExporter;updateCache;ARSpotlightExporter.m;42</pre>

### Reason

**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[NSURL initFileURLWithPath:]: nil string parameter'
### Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/74977/crash_reasons/129734328](https://rink.hockeyapp.net/manage/apps/74977/crash_reasons/129734328)

**Comment by orta** [comment]
Fixed in 2.5.4
