### ISSUE TITLE
Align treatment of artworks with no titles across app / email draft

### ISSUE THREAD

**Issue by garrengotthardt** [artsy/energy#248]
related to: https://github.com/artsy/force/issues/457

Problem:

We're currently displaying artworks inconsistently across Folio when the artwork has no title entered.

example of artwork concerned: https://cms.artsy.net/artworks/cecily-brown-14?current_partner_id=two-palms (we already fall back to "Untitled" across volt)

Solution:
We should display the artwork title as "Untitled" across the board if there is no title entered. Existing implementations to amend include

Already on the artwork page we are doing this:
![img_0093](https://cloud.githubusercontent.com/assets/1863593/20901256/abcf189c-baff-11e6-8e0b-eecd1b18f623.PNG)

However, we are not on the artwork grid view, where they are currently showing up without anything below the image within an artist page / show page
![img_0092](https://cloud.githubusercontent.com/assets/1863593/20901270/c90b711c-baff-11e6-8f85-d192026b16e5.PNG)

![img_0095](https://cloud.githubusercontent.com/assets/1863593/20901423/77f47840-bb00-11e6-9946-ada82dd68670.PNG)

Or on the email draft where it appears as "null"
![img_0094](https://cloud.githubusercontent.com/assets/1863593/20901377/3f682dfa-bb00-11e6-9478-8ea3bfa76fab.PNG)

**Comment by garrengotthardt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Align treatment of artworks with no titles across app / email draft](https://trello.com/c/YxtcjCAp/743-align-treatment-of-artworks-with-no-titles-across-app-email-draft)

**Comment by garrengotthardt** [comment]
@orta as per my note in slack it seems like the quotation marks around titles in email draft subject lines got dropped across the board, if possible to add those back

**Comment by orta** [comment]
This got shipped 👍
