### ISSUE TITLE
Incorrect password causes infinite loading spinner rather than client-side message about incorrect password

### ISSUE THREAD

**Issue by garrengotthardt** [artsy/energy#250]
![img_0010 2](https://cloud.githubusercontent.com/assets/1863593/20978634/94d4575a-bc77-11e6-9c63-1f3647f1f18d.PNG)

@orta seems that inputting an incorrect password results in just an infinite loading spinner and no client-side message about having input an incorrect password appears - let me know what other details i can provide that may be helpful if you're not able to reproduce

**Comment by garrengotthardt** [comment]
happened with both an admin and non-artsy-admin login btw

**Comment by garrengotthardt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Incorrect password causes infinite loading spinner rather than client-side message about incorrect password](https://trello.com/c/OPveU5nV/745-incorrect-password-causes-infinite-loading-spinner-rather-than-client-side-message-about-incorrect-password)

**Comment by orta** [comment]
Fixed this 👍
