### ISSUE TITLE
To address hidden when tapping somewhere else

### ISSUE THREAD

**Issue by starsirius** [artsy/energy#271]
Re: https://artsy.slack.com/archives/C03JWJLLH/p1492082831124275

When composing an email in Folio, the "To" email address field is hidden when I tap somewhere else. It appears again when tap the "To" field, but the hidden behavior causes some partners to think the email address just entered disappeared.

I can reproduce this on an iPad running iOS 9.2 and Folio v2.5.5.

![out](https://cloud.githubusercontent.com/assets/796573/25409815/8a1b2398-29e1-11e7-969b-a73203b0c562.gif)

**Comment by jonallured** [comment]
Awesome reproduction @starsirius, thank you!!!

I'm worried about this one because that looks like a system sheet, not typically something app code can do much about, but I'll see what I can find!

**Comment by starsirius** [comment]
Yeah, I know nothing about the overlay to compose emails. But let's get some investigation and get us familiar with the app! Wanted to learn more about iOS programming at some point. 😛

**Comment by jonallured** [comment]
Well, I took a shot at troubleshooting this, but wasn't able to come up with much. Once I was able to build the app on my phone, reproduction went like this:

* pick any artist
* hit the envelope icon
* select a work
* hit compose
* hit email

I found the resulting sheet buggy in the following ways:

* the vertical cursor bar does not show up when your focus is in any of the email fields (to, cc, bcc, subject)
* when you type in an email address in either the to or bcc fields and then move focus to another field, the address seems to disappear, but once the field regains focus, the address comes back

The gif posted by @starsirius does a great job of showing the buggy behavior and I was always able to reproduce.

## Apple API

The API used to show this sheet is [`MFMailComposeViewController`][mfmail] and can be found in the `AREmailComposer`. This is a pretty simply API - like many of the system-provided sheets, you [provide a delegate][del], show the sheet and when the user is done interacting, you get a callback on that delegate. There's not much more to this than that.

## Delegate

It took me a little while to get my head around the delegate passed to the `MFMailComposeViewController` - the trick is that you can show the email sheet from a few different angles, thus the implementation comes from a superclass. On top of that, there are actually two classes that implement the protocol with identical implementations:

* ARHostViewController
* ARArtworkSetViewController

That first one is (eventually) taken by the `ARArtistViewController` which is what I was working with. The implementations are pretty simple - they're basically an opportunity to create an analytics event and then dismiss the sheet. I didn't see anything unexpected there.

## Conclusion

Not sure where to go from here - I played around on my phone in other apps trying to see if I could convince myself that this was an OS issue, but couldn't reproduce outside of Folio. I guess I'm suspicious of this being a bug at a higher level - maybe we've changing how something works and that change is being inherited by this system sheet?

[mfmail]: https://developer.apple.com/reference/messageui/mfmailcomposeviewcontroller
[del]: https://developer.apple.com/reference/messageui/mfmailcomposeviewcontrollerdelegate

**Comment by alloy** [comment]
> 9.2 and Folio v2.5.5

Does it only apply to these versions or _any_ iOS/Folio version?

> maybe we've changing how something works and that change is being inherited by this system sheet?

That seems unlikely. Afaik `MFMailComposeViewController` runs out-of-proces through XPC, meaning you have no runtime access to its internals _at all_.

Just a silly thought and unlikely the case, but have you used Xcode’s view debugger to look at the view hierarchy when the issue occurs and see if we’re not somehow showing a view over the field?

**Comment by jonallured** [comment]
I was working with my iPhone 7 on 10.3 and the code was at master.

Here's how the view debugger looks while the sheet is open:

<img width="1350" alt="screen shot 2017-04-26 at 4 11 28 pm" src="https://cloud.githubusercontent.com/assets/79799/25457210/1ba1920c-2a9b-11e7-8378-ff709371e760.png">

Just not sure what to do here - how could our app code affect this system sheet? I'm almost thinking about creating a dummy project that just pops one of these sheets as a sanity check...

**Comment by orta** [comment]
I bet it's a UIAppearance issue, we use White/Blacl via that API to colour themes - older builds of iOS didn't have this side effect. You can verify this by changing the theme to white, and then seeing if the text stays black.

**Comment by jonallured** [comment]
@orta was right - I launched the app and turned on the white background setting and these problems went away. To further prove this to myself, I commented out this line: https://github.com/artsy/energy/blob/master/Classes/Theming/ARTheme.m#L29

And the problems went away on the black background as well.

Going to play around with some ideas to fix, but wanted to document this.
