### ISSUE TITLE
Fix NSGenericException in + [NSManagedObject(ActiveRecord) executeFetchRequest:inContext:], line 191

### ISSUE THREAD

**Issue by artsyit** [artsy/energy#33]
### Stacktrace (first of multiple)

<pre>NSManagedObject(ActiveRecord);executeFetchRequest:inContext:;NSManagedObject+ActiveRecord.m;191
NSManagedObject(ActiveRecord);findByAttribute:withValue:inContext:;NSManagedObject+ActiveRecord.m;689
ARSlugResolver;mapSlugsToArtworksForArtworkContainerArray:;ARSlugResolver.m;86
NSSet(ObjectiveSugar);each:;NSSet+ObjectiveSugar.m;31
ARSlugResolver;mapSlugsToArtworksForArtworkContainerArray:;ARSlugResolver.m;85
NSArray(ObjectiveSugar);each:;NSArray+ObjectiveSugar.m;51
ARSlugResolver;mapSlugsToArtworksForArtworkContainerArray:;ARSlugResolver.m;81
ARSlugResolver;resolveSlugsForShows;ARSlugResolver.m;69
ARSlugResolver;resolveAllSlugs;ARSlugResolver.m;23
ARSync;performSync:;ARSync.m;74</pre>

### Reason

**\* Terminating app due to uncaught exception 'NSGenericException', reason: '**\* Collection <__NSCFSet: 0x170477d80> was mutated while being enumerated.'
### Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/74977/crash_reasons/45051142](https://rink.hockeyapp.net/manage/apps/74977/crash_reasons/45051142)

**Comment by orta** [comment]
Hasn't occurred since 2015.
