### ISSUE TITLE
iPad - Settings revamp specs

### ISSUE THREAD

**Issue by lucaderosso** [artsy/energy#51]
### Overview

![folio_ipad_p_settings_overview](https://cloud.githubusercontent.com/assets/539004/9917816/acbdd694-5c91-11e5-9c3e-143efb0062d5.jpg)

VIDEO: https://www.dropbox.com/s/pj115cgylztciff/folio_ipad_P_settings-side-panel.mov?dl=0 

### Views

**Accessing Settings**
![folio_ipad_p_home-black](https://cloud.githubusercontent.com/assets/539004/9912747/29646764-5c77-11e5-936c-6f0d55472221.jpg)

![folio_ipad_p_settings-side-panel](https://cloud.githubusercontent.com/assets/539004/9915578/d3632878-5c85-11e5-9254-43d44ee2f04d.jpg)
- [ ] side panel
- COPY: Hides sensitive information when showing artworks to clients.

**Sync**

![folio_ipad_p_settings-sync](https://cloud.githubusercontent.com/assets/539004/9915558/bb504e8c-5c85-11e5-85a7-818026568177.jpg)
- [ ] sync content view
- COPY: Sync artworks, documents and information to Folio that you've added in CMS. Given the size of images, before syncing, please make sure you have a strong Wi-Fi connection.

**Presentation Mode**

![folio_ipad_p_settings-presentation-mode](https://cloud.githubusercontent.com/assets/539004/9915498/6904704a-5c85-11e5-8e39-d6021c380d67.jpg)
- [ ] edit presentation mode view
- COPY: When Presentation Mode is enabled, all the information and features toggled ON will be hidden. Features toggled OFF will be visible.

**Background**

![folio_ipad_p_settings-background](https://cloud.githubusercontent.com/assets/539004/9915505/6e9a610e-5c85-11e5-9e1f-8b279756e356.jpg)
- [ ] change background view

**Email**

![folio_ipad_p_settings-email_00](https://cloud.githubusercontent.com/assets/539004/9915507/76300af4-5c85-11e5-87cb-2d8053781a9d.jpg)
- [ ] email settings view
- COPY: This signature will be displayed together with any signature specified in your iOS Mail settings.

![folio_ipad_p_settings-email_01](https://cloud.githubusercontent.com/assets/539004/9915509/76317920-5c85-11e5-9575-7be9a30448ba.jpg)
- [ ] email subject editing for one artwork
- COPY: In this field, you can use %a to indicate where you want the artist's name to be placed and %t for the artwork title.

![folio_ipad_p_settings-email_02](https://cloud.githubusercontent.com/assets/539004/9915508/76311656-5c85-11e5-8b0b-0a29f45d96bc.jpg)
- [ ] email subject editing for multiple artworks from multiple artists

![folio_ipad_p_settings-email_03](https://cloud.githubusercontent.com/assets/539004/9915510/763204f8-5c85-11e5-995f-b45c19295e98.jpg)
- [ ] email subject editing for multiple artworks form same artist
- COPY: In this field, you can use %a to indicate where you want the artist's name to be placed.

**Logout**

![folio_ipad_p_settings-logout_00](https://cloud.githubusercontent.com/assets/539004/9915523/8c83b4b8-5c85-11e5-8bed-37f203fc7f47.jpg)
- [ ] logout when only side panel is present

![folio_ipad_p_settings-logout_01](https://cloud.githubusercontent.com/assets/539004/9915527/919d44dc-5c85-11e5-850f-a4bb555e5f17.jpg)
- [ ] logout when settings views are fully exposed

## Landscape
Constraints and distances shown above apply also in landscape view.

![folio_ipad_l_settings-side-panel](https://cloud.githubusercontent.com/assets/539004/9915543/a9d379d6-5c85-11e5-8230-a84e5e84793d.jpg)

![folio_ipad_l_settings-presentation-mode](https://cloud.githubusercontent.com/assets/539004/9915541/a9ccea9e-5c85-11e5-98ff-fb263151562c.jpg)

![folio_ipad_l_settings-sync](https://cloud.githubusercontent.com/assets/539004/9915542/a9d2f15a-5c85-11e5-87da-c0c2fb8510b7.jpg)

**Comment by sarahscott** [comment]
Finished
