### ISSUE TITLE
Fix NSInvalidArgumentException in + [ARRouter newPartnerLocationArtworksRequestWithPartnerID:locationID:page:], line 268

### ISSUE THREAD

**Issue by artsyit** [artsy/energy#61]
### Stacktrace

<pre>ARRouter;newPartnerLocationArtworksRequestWithPartnerID:locationID:page:;ARRouter.m;268
ARLocationArtworksDownloader;operationTree:operationForObject:continuation:failure:;ARLocationArtworksDownloader.m;22
ARPagingDownloaderOperation;getNextPage;ARPagingDownloaderOperation.m;39</pre>

### Reason

**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
### Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/74977/crash_reasons/44315529](https://rink.hockeyapp.net/manage/apps/74977/crash_reasons/44315529)

**Comment by orta** [comment]
Hasn't occurred since 2015.
