### ISSUE TITLE
iOS 9 isn't showing document thumbnails

### ISSUE THREAD

**Issue by sarahscott** [artsy/energy#75]
Reproducible in simulator and on hardware:

![simulator screen shot oct 13 2015 4 15 29 pm](https://cloud.githubusercontent.com/assets/2712962/10467057/a6d1fef6-71c5-11e5-9b80-f6c120bc2410.png)

I checked the destination path for the simulator and the thumbnails are actually being generated, which is good news.

**Comment by orta** [comment]
#76 and #78 fix this
