### ISSUE TITLE
Folio should support multiple artists along with volt and force

### ISSUE THREAD

**Issue by garrengotthardt** [artsy/energy#91]
Reviving this issue in this newer repo — we should support multiple artists attached to artworks as we do in force/volt by ensuring:
- [ ] both artist names are included on the individual artwork view and in artwork grid view in shows and albums
- [ ] a given artwork is included in any of the artist's sections with which it is associated

ie: https://www.artsy.net/artwork/richard-hoeck-1997

Folio:
![unnamed](https://github-cloud.s3.amazonaws.com/assets%2F1863593%2F10957541%2F4b617ffe-8333-11e5-97c8-322702a351bb.png)

Volt:
<img width="1264" alt="screen shot 2015-10-28 at 12 41 32 pm" src="https://github-cloud.s3.amazonaws.com/assets%2F1863593%2F10957571%2F99b2edb4-8333-11e5-9605-b6ef4071a4b0.png">

Force:
![screen shot 2015-11-04 at 8 26 11 pm](https://github-cloud.s3.amazonaws.com/assets%2F1863593%2F10957573%2Fa10c78dc-8333-11e5-81b1-42e96efb4f31.png)

**Comment by orta** [comment]
This is in  👍
