### ISSUE TITLE
Decide how to display presentation mode settings when there are no settings

### ISSUE THREAD

**Issue by sarahscott** [artsy/energy#95]
If a partner has no works with prices, published work, or confidential notes, what should be shown in the Edit Presentation Mode view? Should the presentation mode setting buttons be visible/disabled in the master settings menu at all in this case?

@lucaderosso @garrengotthardt 

![](https://cloud.githubusercontent.com/assets/539004/9915498/6904704a-5c85-11e5-8e39-d6021c380d67.jpg)

**Comment by garrengotthardt** [comment]
@sarah assuming its easier on your end and also avoids having a blank panel we could just update the copy at the bottom to say: "When Presentation Mode is enabled, all information related to features toggled ON will be hidden. Information that has been entered related to features toggled OFF will be visible."

**Comment by lucaderosso** [comment]
I support this solution.

**Comment by orta** [comment]
So this answer assumes that we show all of the options every time, which currently we don't.

 For example institutions don't want to feel like this app is super commercial, which is why we hide the "Price"-y options. We're totally cool to show all of them, however it's worth taking into account that not all partners ( or collectors ) would want to know all of Folio's features.

**Comment by sarahscott** [comment]
@garrengotthardt @lucaderosso yeah, i agree with orta that partners who can't publish works shouldn't see the 'Hide Unpublished Works' album for example, especially going forward with folio-only subscriptions.

an institutional partner or collector wouldn't be able to use any of the above options.

**Comment by sarahscott** [comment]
- Collector Folio: Remove entire concept of Presentation Mode
- Galleries/Institutions: use @garrengotthardt 's new copy, always show the "Hide Confidential Notes" and "Hide Artwork Edit Button" toggles, and hide publishing/pricing-related toggles as needed.

thanks for the feedback @lucaderosso, @garrengotthardt, and @orta!

**Comment by sarahscott** [comment]
Fixed; ended up with presentation mode settings that exist for all Folio users
